import Head from 'next/head'
import Image from 'next/image'
import styles from '../styles/Home.module.css'
import Home from './Home/Home'

export default function index() {
  return (
    <div className={styles.container}>
      <Head>
        <title>ROOMWALA | 3.0</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main className={styles.main}>
        <Home/>
      </main>

    </div>
  )
}
